config/routes.rb
Rails.application.routes.draw do

  root to: "submissions#index"

  get 'sessions/create'

  get 'sessions/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  resources :comment_votes

  resources :comments do
    member do
      get 'upvote' => 'comments#upvote'
    end
  end  
  
  resources :submissions do
    member do
      get 'upvote' => 'submissions#upvote'
    end
  end  
  

  resources :submission_votes
  resources :submissions
  resources :votes
  resources :contributions
  resources :users
  
  get '/asks', to: 'submissions#ask'
  get '/news', to: 'submissions#news'
  
  get '/threads', to: 'comments#threads'


  scope '/api' do
    scope '/v1' do
      
      
      scope '/users' do
        get '/' => 'api_users#index'
        post '/'=> 'api_users#create'
        scope '/:id' do
          get '/' => 'api_users#show'
          put '/' => 'api_users#update'
          patch '/' => 'api_users#update'
        end
      end
      
      scope '/submissions' do
        get '/' => 'api_submissions#index'
        #post '/' => 'api_submissions#create'
        scope '/:id' do
          get '/' => 'api_submissions#show'
          post '/reply' => 'api_submissions#reply'
          scope '/vote' do
            post '/' => 'api_submissions#vote'
          end
          
        end
      end
      
      scope '/comments' do
        get '/' => 'api_comments#index'
        scope '/:id' do
          get '/' => 'api_comments#show'
          post '/reply' => 'api_comments#reply'
          scope '/vote' do
            post '/' => 'api_comments#vote'
          end
        end
      end 
      
      scope '/asks' do
        get '/' => 'api_submissions#asks'
        post '/' => 'api_submissions#create'
      end 

      scope '/news' do
        get '/' => 'api_submissions#news'
        post '/' => 'api_submissions#create'
      end 
    
      scope '/threads' do
        get '/' => 'api_comments#threads'
      end
    end
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  
  validates :title, presence: true, uniqueness: false
  #validates :message, length: { maximum: 10000 }
  
  has_many :comments, class_name: "Comment", foreign_key: "submission_id", :dependent => :destroy
  has_many :submission_votes, :dependent => :destroy
  
  validate :urlXORmessage
  validates :url, :format => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix

  private
    def urlXORmessage
      unless url.blank? ^ message.blank?
        errors.add(:base, "Submit a url or a message, not both")
      end
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.order(created_at: :desc)
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @comment = Comment.new
    
    if (current_user) 
      @comment.user_id = current_user.id
    else 
      @comment.user_id = nil
    end
    
    @comment.submission_id = @submission.id
  
    @comments = Comment.where("submission_id = ? AND parent_id IS NULL", params[:id]).order(created_at: :asc)
    @replies = Comment.where("submission_id = ? AND parent_id IS NOT NULL", params[:id]).order(parent_id: :asc ,created_at: :asc)
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
    @submission.user_id = current_user.id
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)
    
    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @userId = current_user.id
    @submissionId = params[:id]
    
    @vote = SubmissionVote.find_by(user_id: @userId, submission_id: @submissionId)
    
    if (@vote.nil?) 
      SubmissionVote.create(user_id: @userId, submission_id: @submissionId, value: 1)
    else 
      @vote.destroy
    end
    redirect_to(:back)  
  end
  
  def ask
    @submissions = Submission.where("url = ''").order(created_at: :desc)
  end
  
  def news
    @submissions = Submission.where("message = ''").order(created_at: :desc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:user_id, :title, :url, :message)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  def currentUserHasUpVotedTheSubmission(submission)
    submission.submission_votes.each do |vote|
      if (vote.user_id == current_user.id)
        return true
      end
    end
    return false
  end
  
  def isCurrentUserSubmission(submission)
    if (submission.user_id == current_user.id)
      return true
    else return false
    end
  end
  
end

app/views/submissions/_form.html.erb
  <%= form_for(@submission) do |f| %>
    <% if @submission.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>
  
        <ul>
        <% @submission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
  
    <div class="field">
      <%= f.hidden_field :user_id, :value => @submission.user_id%>
    </div>
    
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :url %><br>
        <%= f.url_field :url, :placeholder => "http:\\www.google.es" %> 
    </div>
    
    <b> or </b>
    
    <div class="field">
      <%= f.label :message %><br>
      <%= f.text_area :message %>
    </div> 
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/submissions/ask.html.erb
<div id="navbar">
  <div class="menu">
    <ul>
      <li><a href="/">Hacker News</a></li>
      <li><a href="/submissions">News</a></li>
      <li><a href="/comments">Comments</a></li>
      <li class="active"><a href="/asks">Asks</a></li>
      <% if current_user %>
        <li><a href="/submissions/new">Submit</a></li>
      <% end %>
      <% if current_user %>
        <li><a href="/threads">Threads</a></li>
      <% end %>
      
      <% if current_user %>
        <li class ="float-right white-text" style="display:inline-flex">
          <a class="float-right" href="/users/<%= current_user.id %>">
            Hi o/ <%=current_user.name %>
          <div class="user-image float-right" style="background-image:url(<%= current_user.picture %>?sz=45);"><div>
          </a>    
        </li>
        <li class=float-right><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
      <% else %>
        <li class ="float-right"><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
      <div class="clearFloat"></div>
    </ul>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="content-wrapper">
<table>


  <tbody>

      
    <% @submissions.each_with_index do |submission, index| %>
      <tr class ="">
        <td>
        <span><%= index+1 %>. </span>
        <% if !current_user%>
          <% elsif !isCurrentUserSubmission(submission) and !currentUserHasUpVotedTheSubmission(submission) %>
            <span style="color:gray;"><%= link_to "▲", upvote_submission_path(submission) %></span>
          <% elsif !isCurrentUserSubmission(submission) %>
            <span style="color:green;"><%= link_to "▲", upvote_submission_path(submission), {:style=>'color:green;'}%></span>
          <% else%>
            <span style="color:orange;">*</span>
          <% end %>
        <%= link_to submission.title, submission %>
        </td>
      </tr>
      <tr class ="submission-info">
        <td>points <%= submission.submission_votes.size + 1 %> posted by <%= link_to submission.user.name, submission.user %>
          <span><%= link_to distance_of_time_in_words(submission.created_at, Time.now)+" ago", submission %></span>
          <% if submission.comments.size == 0 %>
          <span> | <%= link_to "Discuss", submission %> </span>
          <% else %>
          <span> | <%= link_to submission.comments.size.to_s+" comments", submission %> </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/submissions/index.html.erb
<div id="navbar">
  <div class="menu">
    <ul>
      <li class="active"><a href="/">Hacker News</a></li>
      <li><a href="/news">News</a></li>
      <li><a href="/comments">Comments</a></li>
      <li><a href="/asks">Asks</a></li>
      <% if current_user %>
        <li><a href="/submissions/new">Submit</a></li>
      <% end %>
      <% if current_user %>
        <li><a href="/threads">Threads</a></li>
      <% end %>
      
      <% if current_user %>
        <li class ="float-right white-text" style="display:inline-flex">
          <a class="float-right" href="/users/<%= current_user.id %>">
            Hi o/ <%=current_user.name %>
          <div class="user-image float-right" style="background-image:url(<%= current_user.picture %>?sz=45);"><div>
          </a>    
        </li>
        <li class=float-right><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
      <% else %>
        <li class ="float-right"><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
      <div class="clearFloat"></div>
    </ul>
  </div>
</div>

<p id="notice"><%= notice %></p>
<div class="content-wrapper">
  <h2> What are hackers thinking ?</h2>
  <table class="content-wrapper">
    <tbody>
      <% @submissions.each_with_index do |submission, index| %>
        <tr class ="">
            <td>
            <span><%= index+1 %>. </span>
            <% if !current_user%>
            <% elsif !isCurrentUserSubmission(submission) and !currentUserHasUpVotedTheSubmission(submission) %>
              <span style="color:gray;"><%= link_to "▲", upvote_submission_path(submission) %></span>
            <% elsif !isCurrentUserSubmission(submission) %>
              <span style="color:green;"><%= link_to "▲", upvote_submission_path(submission), {:style=>'color:green;'}%></span>
            <% else %>
              <span style="color:orange;">*</span>
            <% end %>
              
            <% if submission.message.empty? %>
              <a href="<%= submission.url %>"><%= submission.title %></a>
              <span>(<%= link_to submission.url, submission.url %>)</span>
            <% else %>
              <%= link_to submission.title, submission %>
            <% end %>
          </td>
        </tr>
        <tr class ="submission-info">
          <td>points <%= submission.submission_votes.size + 1 %> posted by <%= link_to submission.user.name, submission.user %>
            <span><%= link_to distance_of_time_in_words(submission.created_at, Time.now)+" ago", submission %></span>
            <% if submission.comments.size == 0 %>
            <span> | <%= link_to "Discuss", submission %> </span>
            <% else %>
            <span> | <%= link_to submission.comments.size.to_s+" comments", submission %> </span>
            <% end %>
            <br>
            </td>
          </tr>
        </tr>
        
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/submissions/new.html.erb
 <div id="navbar">
  <div class="menu">
    <ul>
      <li><a href="/">Hacker News</a></li>
      <li><a href="/submissions">News</a></li>
      <li><a href="/comments">Comments</a></li>
      <li><a href="/asks">Asks</a></li>
      <% if current_user %>
        <li class="active"><a href="/submissions/new">Submit</a></li>
      <% end %>
      <% if current_user %>
        <li><a href="/threads">Threads</a></li>
      <% end %>
      
      <% if current_user %>
        <li class ="float-right white-text" style="display:inline-flex">
          <a class="float-right" href="/users/<%= current_user.id %>">
            Hi o/ <%=current_user.name %>
          <div class="user-image float-right" style="background-image:url(<%= current_user.picture %>?sz=45);"><div>
          </a>    
        </li>
        <li class=float-right><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
      <% else %>
        <li class ="float-right"><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
      <div class="clearFloat"></div>
    </ul>
  </div>
</div>
<div class="content-wrapper">
  <h2>Create new Submission</h2>
  
  <% if current_user %>
    <%= render 'form' %>
  <% end %>
</div>

app/views/submissions/news.html.erb
<div id="navbar">
  <div class="menu">
    <ul>
      <li class="active"><a href="/">Hacker News</a></li>
      <li><a href="/submissions">News</a></li>
      <li><a href="/comments">Comments</a></li>
      <li><a href="/asks">Asks</a></li>
      <% if current_user %>
        <li><a href="/submissions/new">Submit</a></li>
      <% end %>
      <% if current_user %>
        <li><a href="/threads">Threads</a></li>
      <% end %>
      
      <% if current_user %>
        <li class ="float-right white-text" style="display:inline-flex">
          <a class="float-right" href="/users/<%= current_user.id %>">
            Hi o/ <%=current_user.name %>
          <div class="user-image float-right" style="background-image:url(<%= current_user.picture %>?sz=45);"><div>
          </a>    
        </li>
        <li class=float-right><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
      <% else %>
        <li class ="float-right"><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
      <div class="clearFloat"></div>
    </ul>
  </div>
</div>

<div class="content-wrapper">
  <p id="notice"><%= notice %></p>
  <table>
    <tbody>
      <% @submissions.each_with_index do |submission, index| %>
        <tr class ="">
          <td>
            <span><%= index+1 %>. </span>
            <% if !current_user%>
            <% elsif !isCurrentUserSubmission(submission) and !currentUserHasUpVotedTheSubmission(submission) %>
              <span style="color:gray;"><%= link_to "▲", upvote_submission_path(submission) %></span>
            <% elsif !isCurrentUserSubmission(submission) %>
              <span style="color:green;"><%= link_to "▲", upvote_submission_path(submission), {:style=>'color:green;'}%></span>
            <% else%>
              <span style="color:orange;">*</span>
            <% end %>
            <a href="<%= submission.url %>"><%= submission.title %></a>
            <span>(<%= link_to submission.url, submission.url %>)</span>
          </td>
        </tr>
        <tr class ="submission-info">
          <td>points <%= submission.submission_votes.size + 1 %> posted by <%= link_to submission.user.name, submission.user %>
            <span><%= link_to distance_of_time_in_words(submission.created_at, Time.now)+" ago", submission %></span>
            <% if submission.comments.size == 0 %>
            <span> | <%= link_to "Discuss", submission %> </span>
            <% else %>
            <span> | <%= link_to submission.comments.size.to_s+" comments", submission %> </span>
            <% end %>
            </td>
          </tr>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/submissions/show.html.erb
<div id="navbar">
  <div class="menu">
    <ul>
      <li><a href="/">Hacker News</a></li>
      <li><a href="/submissions">News</a></li>
      <li><a href="/comments">Comments</a></li>
      <li><a href="/asks">Asks</a></li>
      <% if current_user %>
        <li><a href="/submissions/new">Submit</a></li>
      <% end %>
      <% if current_user %>
        <li><a href="/threads">Threads</a></li>
      <% end %>
      
      <% if current_user %>
        <li class ="float-right white-text" style="display:inline-flex">
          <a class="float-right" href="/users/<%= current_user.id %>">
            Hi o/ <%=current_user.name %>
          <div class="user-image float-right" style="background-image:url(<%= current_user.picture %>?sz=45);"><div>
          </a>    
        </li>
        <li class=float-right><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
      <% else %>
        <li class ="float-right"><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
      <% end %>
      <div class="clearFloat"></div>
    </ul>
  </div>
</div>
<div class="content-wrapper">
  <p id="notice"><%= notice %></p>
  
  <% if !current_user %>
  <% elsif !currentUserHasUpVotedTheSubmission(@submission) and !isCurrentUserSubmission(@submission)%>
    <%= link_to "▲ ", upvote_submission_path(@submission) %>
  <% elsif !isCurrentUserSubmission(@submission)%>
    <span style="color:green;"><%= link_to "▲ ", upvote_submission_path(@submission), {:style=>'color:green;'}%></span>
  <% else %>
    <span style="color:orange;">* </span>
  <% end %>
  
  <% if @submission.message.empty? %>
    <a href="<%= @submission.url %>"><%= @submission.title %></a>
    <span>(<%= link_to @submission.url, @submission.url %>)</span>
  <% else %>
    <%= link_to @submission.title, @submission %>
  <% end %>
  
  <br>
  
  points <%= @submission.submission_votes.size + 1 %> by <%= link_to @submission.user.name, @submission.user %> |
  <%= link_to distance_of_time_in_words(@submission.created_at, Time.now)+" ago", @submission %> |
  
  
  <% if @comments.size == 0 %>
    <%= link_to 'discuss', @submission %>
  <% elsif (@comments.size + @replies.size) == 1 %>
    <%= link_to "1 comment" , @submission %>
  <% else %>
    <%= link_to "#{@comments.size + @replies.size} comments" , @submission %>
  <% end %>
  
  
  
  <% if !@submission.message.empty? %>
    <br><%= @submission.message %> <br><br>
  <% end %>
  
  <% if current_user %>
    <%= render 'comments/form' %>
  <% end %>
  
  <% @comments.each do |comment| %>
    <p>
      <% if !current_user %>
      <% else %>
        <% if !currentUserHasUpVotedTheComment(comment) and !isCurrentUserComment(comment) %>
            <%= link_to "▲", upvote_comment_path(comment) %>
        <% elsif !isCurrentUserComment(comment) %>
          <span style="color:green;"><%= link_to "▲", upvote_comment_path(comment), {:style=>'color:green;'}%></span>
        <% else%>
          <span style="color:orange;">*</span>
        <% end %>
      <% end %>
      <%= link_to comment.user.name, comment.user %> |
      <%= link_to distance_of_time_in_words(comment.created_at, Time.now)+" ago", comment %><br>
      <%= comment.message %><br>
      <%= link_to 'Reply', comment%>
    </p>
    
    <% @replies.each do |reply| %>
      
      <% if reply.parent_id == comment.id %>
        <div style="margin-left: 30px;"> 
          <p>
            <% if !current_user %>
            <% elsif !currentUserHasUpVotedTheComment(reply) and !isCurrentUserComment(reply) %>
                <%= link_to "▲", upvote_comment_path(reply) %>
            <% elsif !isCurrentUserComment(reply) %>
              <span style="color:green;"><%= link_to "▲", upvote_comment_path(reply), {:style=>'color:green;'}%></span>
            <% else%>
              <span style="color:orange;">*</span>
            <% end %>
            <%= link_to reply.user.name, reply.user %> |
            <%= link_to distance_of_time_in_words(comment.created_at, Time.now)+" ago", comment %><br>
            <%= reply.message %>
          </p>
        </div>
        <% end %>
    <% end %>
  <% end %>
</div>